INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Administradora de Riesgos de Salud de las Fuerzas Armadas'),
	 ('Administradora de Riesgos de Salud Salud Segura'),
	 ('Administradora de Riesgos de Salud Seguro Médico para los Maestros'),
	 ('Administradora de Subsidios Sociales'),
	 ('AMERIPOL'),
	 ('Archivo General de la Nación'),
	 ('Area IV de Salud'),
	 ('Áreas de Salud (DAS) – I'),
	 ('Áreas de Salud (DAS) – II'),
	 ('Áreas de Salud (DAS) – III');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Áreas de Salud (DAS) – IV'),
	 ('Áreas de Salud (DAS) – V'),
	 ('Áreas de Salud (DAS) – VI'),
	 ('Áreas de Salud (DAS) – VII'),
	 ('Áreas de Salud (DAS) – VIII'),
	 ('Aseguradora Agropecuaria Dominicana'),
	 ('Autoridad Nacional de Asuntos Marítimos'),
	 ('Autoridad Portuaria Dominicana'),
	 ('Ayuntamiento de Altamira'),
	 ('Ayuntamiento de Arenoso');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Azua de Compostela'),
	 ('Ayuntamiento de Baitoa'),
	 ('Ayuntamiento de Bajos de Haina'),
	 ('Ayuntamiento de Baní'),
	 ('Ayuntamiento de Bánica'),
	 ('Ayuntamiento de Barahona'),
	 ('Ayuntamiento de Bayaguana'),
	 ('Ayuntamiento de Bisonó'),
	 ('Ayuntamiento de Boca Chica'),
	 ('Ayuntamiento de Bohechío');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Bonao'),
	 ('Ayuntamiento de Cabral'),
	 ('Ayuntamiento de Cabrera'),
	 ('Ayuntamiento de Cambita Garabitos'),
	 ('Ayuntamiento de Castañuelas'),
	 ('Ayuntamiento de Castillo'),
	 ('Ayuntamiento de Cayetano Germosén'),
	 ('Ayuntamiento de Cevicos'),
	 ('Ayuntamiento de Comendador'),
	 ('Ayuntamiento de Constanza');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Consuelo'),
	 ('Ayuntamiento de Cotuí'),
	 ('Ayuntamiento de Cristóbal'),
	 ('Ayuntamiento de Dajabón'),
	 ('Ayuntamiento de Duvergé'),
	 ('Ayuntamiento de El Cercado'),
	 ('Ayuntamiento de El Factor'),
	 ('Ayuntamiento de El Llano'),
	 ('Ayuntamiento de El Peñón'),
	 ('Ayuntamiento de El Pino');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de El Seibo'),
	 ('Ayuntamiento de El Valle'),
	 ('Ayuntamiento de Enriquillo'),
	 ('Ayuntamiento de Esperanza'),
	 ('Ayuntamiento de Estebanía'),
	 ('Ayuntamiento de Eugenio María de Hostos'),
	 ('Ayuntamiento de Fantino'),
	 ('Ayuntamiento de Fundación'),
	 ('Ayuntamiento de Galván'),
	 ('Ayuntamiento de Gaspar Hernández');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Guananico'),
	 ('Ayuntamiento de Guayabal'),
	 ('Ayuntamiento de Guayacanes'),
	 ('Ayuntamiento de Guaymate'),
	 ('Ayuntamiento de Guayubín'),
	 ('Ayuntamiento de Hato Mayor'),
	 ('Ayuntamiento de Higüey'),
	 ('Ayuntamiento de Hondo Valle'),
	 ('Ayuntamiento de Imbert'),
	 ('Ayuntamiento de Jamao al Norte');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Jánico'),
	 ('Ayuntamiento de Jaquimeyes'),
	 ('Ayuntamiento de Jarabacoa'),
	 ('Ayuntamiento de Jima Abajo'),
	 ('Ayuntamiento de Jimaní'),
	 ('Ayuntamiento de Juan de Herrera'),
	 ('Ayuntamiento de Juan Santiago'),
	 ('Ayuntamiento de La Ciénaga'),
	 ('Ayuntamiento de La Concepción de La Vega'),
	 ('Ayuntamiento de La Descubierta');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de La Romana'),
	 ('Ayuntamiento de Laguna Salada'),
	 ('Ayuntamiento de Las Charcas'),
	 ('Ayuntamiento de Las Guáranas'),
	 ('Ayuntamiento de Las Matas de Farfán'),
	 ('Ayuntamiento de Las Matas de Santa Cruz'),
	 ('Ayuntamiento de Las Salinas'),
	 ('Ayuntamiento de Las Terrenas'),
	 ('Ayuntamiento de Las Yayas de Viajama'),
	 ('Ayuntamiento de Licey al Medio');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Loma de Cabrera'),
	 ('Ayuntamiento de Los Alcarrizos'),
	 ('Ayuntamiento de Los Cacaos'),
	 ('Ayuntamiento de Los Hidalgos'),
	 ('Ayuntamiento de Los Ríos'),
	 ('Ayuntamiento de Luperón'),
	 ('Ayuntamiento de Maimón'),
	 ('Ayuntamiento de Mao'),
	 ('Ayuntamiento de Matanzas'),
	 ('Ayuntamiento de Mella');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Miches'),
	 ('Ayuntamiento de Moca'),
	 ('Ayuntamiento de Monción'),
	 ('Ayuntamiento de Monte Cristi'),
	 ('Ayuntamiento de Monte Plata'),
	 ('Ayuntamiento de Nagua'),
	 ('Ayuntamiento de Neiba'),
	 ('Ayuntamiento de Nizao'),
	 ('Ayuntamiento de Oviedo'),
	 ('Ayuntamiento de Padre las Casas');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Paraíso'),
	 ('Ayuntamiento de Partido'),
	 ('Ayuntamiento de Pedernales'),
	 ('Ayuntamiento de Pedro Brand'),
	 ('Ayuntamiento de Pedro Santana'),
	 ('Ayuntamiento de Pepillo Salcedo'),
	 ('Ayuntamiento de Peralta'),
	 ('Ayuntamiento de Peralvillo'),
	 ('Ayuntamiento de Piedra Blanca'),
	 ('Ayuntamiento de Pimentel');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Polo'),
	 ('Ayuntamiento de Postrer Río'),
	 ('Ayuntamiento de Pueblo Viejo'),
	 ('Ayuntamiento de Puerto Plata'),
	 ('Ayuntamiento de Puñal'),
	 ('Ayuntamiento de Quisqueya'),
	 ('Ayuntamiento de Ramón Santana'),
	 ('Ayuntamiento de Rancho Arriba'),
	 ('Ayuntamiento de Restauración'),
	 ('Ayuntamiento de Río San Juan');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Sabana de la Mar'),
	 ('Ayuntamiento de Sabana Grande de Boyá'),
	 ('Ayuntamiento de Sabana Grande de Palenque'),
	 ('Ayuntamiento de Sabana Iglesia'),
	 ('Ayuntamiento de Sabana Larga'),
	 ('Ayuntamiento de Sabana Yegua'),
	 ('Ayuntamiento de Salcedo'),
	 ('Ayuntamiento de Samaná'),
	 ('Ayuntamiento de San Antonio de Guerra'),
	 ('Ayuntamiento de San Cristóbal');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de San Francisco de Macorís'),
	 ('Ayuntamiento de San Gregorio de Nigua'),
	 ('Ayuntamiento de San Ignacio de Sabaneta'),
	 ('Ayuntamiento de San José de las Matas'),
	 ('Ayuntamiento de San José de Los Llanos'),
	 ('Ayuntamiento de San José de Ocoa'),
	 ('Ayuntamiento de San Juan de la Maguana'),
	 ('Ayuntamiento de San Pedro de Macorís'),
	 ('Ayuntamiento de San Rafael del Yuma'),
	 ('Ayuntamiento de San Víctor');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Sánchez'),
	 ('Ayuntamiento de Santiago de los Caballeros'),
	 ('Ayuntamiento de Santo Domingo Este'),
	 ('Ayuntamiento de Santo Domingo Norte'),
	 ('Ayuntamiento de Santo Domingo Oeste'),
	 ('Ayuntamiento de Sosúa'),
	 ('Ayuntamiento de Tábara Arriba'),
	 ('Ayuntamiento de Tamayo'),
	 ('Ayuntamiento de Tamboril'),
	 ('Ayuntamiento de Tenares');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Vallejuelo'),
	 ('Ayuntamiento de Vicente Noble'),
	 ('Ayuntamiento de Villa Altagracia'),
	 ('Ayuntamiento de Villa González'),
	 ('Ayuntamiento de Villa Hermosa'),
	 ('Ayuntamiento de Villa Isabela'),
	 ('Ayuntamiento de Villa Jaragua'),
	 ('Ayuntamiento de Villa La Mata'),
	 ('Ayuntamiento de Villa los Almácigos'),
	 ('Ayuntamiento de Villa Montellano');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ayuntamiento de Villa Riva'),
	 ('Ayuntamiento de Villa Tapia'),
	 ('Ayuntamiento de Villa Vásquez'),
	 ('Ayuntamiento de Yaguate'),
	 ('Ayuntamiento de Yamasá'),
	 ('Ayuntamiento del Distrito Nacional'),
	 ('Ayuntamiento Distrito Municipal de Hato del Yaque'),
	 ('Banco Agrícola de la República Dominicana'),
	 ('Banco Central de la República Dominicana'),
	 ('Banco de Reservas de la República Dominicana');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Banco Nacional de las Exportaciones'),
	 ('Biblioteca Nacional Pedro Henríquez Ureña'),
	 ('Caja de Ahorros para Obreros y Monte de Piedad'),
	 ('Caja de Pensiones y Jubilaciones para Choferes'),
	 ('Cámara de Cuentas de la República Dominicana'),
	 ('Cámara de Diputados'),
	 ('Centro Antirrábico Nacional'),
	 ('Centro Cardio-Neuro Oftalmológico y Trasplante'),
	 ('Centro Cultural de las Telecomunicaciones'),
	 ('Centro de Atención Integral para la Discapacidad');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Centro de Atención Integral para la Discapacidad de Santiago'),
	 ('Centro de Atención Integral para la Discapacidad Luperon Santo Domingo'),
	 ('Centro de Atención Integral para la Discapacidad San Juan de la Maguana'),
	 ('Centro de Atención Primaria Villa Liberación San Juan'),
	 ('Centro de Capacitación en Planificación e Inversión Pública'),
	 ('Centro de Capacitación en Política y Gestión Fiscal'),
	 ('Centro de Desarrollo y Competitividad Industrial'),
	 ('Centro de Educación Médica de Amistad Dominico-Japonesa'),
	 ('Centro de Exportación e Inversión de la República Dominicana'),
	 ('Centro de Gastroenterología de la Ciudad Sanitaria Dr. Luis Eduardo Aybar');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Centro de Información Gubernamental'),
	 ('Centro de Operaciones de Emergencia'),
	 ('Centro de Salud Integral Bella Vista'),
	 ('Centro Educativo Pedro Domínguez Garabito'),
	 ('Centro Especializado en Atención de Salud Juan XXIII'),
	 ('Centro Nacional de Artesanía'),
	 ('Centro Nacional de Ciberseguridad'),
	 ('Círculo Deportivo de las Fuerzas Armadas'),
	 ('Ciudad Sanitaria Luis Eduardo Aybar'),
	 ('Comandancia General de la Armada de la República Dominicana');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Comandancia General de la Fuerza Aérea de la República Dominicana'),
	 ('Comandancia General del Ejército de la República Dominicana'),
	 ('Comando Conjunto de las Reservas de las FFAA'),
	 ('Comedores Económicos del Estado'),
	 ('Comisión de Fomento a la Tecnificación del Sistema Nacional de Riego'),
	 ('Comisión de Reforma de la Empresa Pública'),
	 ('Comisión Ejecutiva para la Reforma del Sector Salud'),
	 ('Comisión Hípica Nacional'),
	 ('Comisión Internacional Asesora de Ciencia y Tecnología (CIACT)'),
	 ('Comisión Internacional Asesora de Ciencia y Tecnología (CIACT)');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Comisión Nacional de Defensa de la Competencia'),
	 ('Comisión Nacional de Emergencias'),
	 ('Comisión Nacional de Energía'),
	 ('Comisión Nacional de Espectáculos Públicos y Radiofonía'),
	 ('Comisión Nacional de Negociaciones Comerciales'),
	 ('Comisión Permanente de Efemérides Patrias'),
	 ('Comisión Permanente de la Feria del Libro'),
	 ('Comisión Permanente para la Reforma y Modernización de las Fuerzas Armadas'),
	 ('Comisión Presidencial de Apoyo al Desarrollo Barrial'),
	 ('Comisión Presidencial de Apoyo al Desarrollo Provincial');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Comisión Presidencial de Política Farmacéutica Nacional'),
	 ('Comisión Presidencial para el Desarrollo del Mercado Hipotecario y el Fideicomiso'),
	 ('Comisión Presidencial para la Modernización y Seguridad'),
	 ('Comisión Presidencial para la Modernización y Seguridad Portuaria'),
	 ('Comisión Reguladora de Prácticas Desleales en el Comercio y Medidas de Salvaguardas'),
	 ('Comisionado de Apoyo a la Reforma y Modernización de la Justicia'),
	 ('Comité de Retiro de la Policía Nacional'),
	 ('Comité Ejecutor de Infraestructuras de Zonas Turísticas'),
	 ('Comité Ejecutor de Infraestructuras de Zonas Turísticas'),
	 ('Comité Nacional Contra el Lavado de Activos');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Consejo Asesor del Presidente de la República'),
	 ('Consejo Asesor en Materia de Lucha Anticorrupción de la Presidencia de la República'),
	 ('Consejo de Administración y Regulación de Taxis'),
	 ('Consejo de Asesores Económicos del Poder Ejecutivo'),
	 ('Consejo de Coordinación de la Zona Especial de Desarrollo Fronterizo'),
	 ('Consejo de Fomento Turistico'),
	 ('Consejo de la Medalla Presidencial al Mérito Civil'),
	 ('Consejo de Ministros'),
	 ('Consejo de Seguridad y Defensa Nacional'),
	 ('Consejo del Poder Judicial');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Consejo del Sistema Nacional de Atención a Emergencias y Seguridad 9-1-1'),
	 ('Consejo Dominicano de Pesca y Acuicultura'),
	 ('Consejo Dominicano para la Calidad'),
	 ('Consejo Económico y Social'),
	 ('Consejo Estatal del Azúcar'),
	 ('Consejo Intersectorial para la Política del Libro'),
	 ('Consejo Nacional de Agricultura'),
	 ('Consejo Nacional de Agricultura Ecológica'),
	 ('Consejo Nacional de Agricultura Orgánica'),
	 ('Consejo Nacional de Comercio Exterior');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Consejo Nacional de Competitividad'),
	 ('Consejo Nacional de Cultura'),
	 ('Consejo Nacional de Discapacidad'),
	 ('Consejo Nacional de Drogas'),
	 ('Consejo Nacional de Educación'),
	 ('Consejo Nacional de Educación Superior'),
	 ('Consejo Nacional de Estancias Infantiles'),
	 ('Consejo Nacional de Estrategia Deportiva'),
	 ('Consejo Nacional de Fronteras'),
	 ('Consejo Nacional de Investigaciones Agropecuarias y Forestales');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Consejo Nacional de la Magistratura'),
	 ('Consejo Nacional de la Persona Envejeciente'),
	 ('Consejo Nacional de la Vivienda Económica'),
	 ('Consejo Nacional de Mecenazgo'),
	 ('Consejo Nacional de Medio Ambiente y Recursos Naturales'),
	 ('Consejo Nacional de Población y Familia'),
	 ('Consejo Nacional de Prevención'),
	 ('Consejo Nacional de Producción Pecuaria'),
	 ('Consejo Nacional de Promoción y Apoyo a la Micro'),
	 ('Consejo Nacional de Protección Radiológica');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Consejo Nacional de Reestructuración Industrial'),
	 ('Consejo Nacional de Reforma del Estado'),
	 ('Consejo Nacional de Salud'),
	 ('Consejo Nacional de Seguridad Ciudadana'),
	 ('Consejo Nacional de Seguridad Social'),
	 ('Consejo Nacional de Seguridad y Salud Ocupacional'),
	 ('Consejo Nacional de Trasplante'),
	 ('Consejo Nacional de Valores'),
	 ('Consejo Nacional de Zonas Financieras Internacionales'),
	 ('Consejo Nacional de Zonas Francas de Exportación');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Consejo Nacional Interinstitucional de Reforma y Modernización de la Educación y Formación Técnico Profesional'),
	 ('Consejo Nacional para el Cambio Climático y Mecanismo de Desarrollo Limpio'),
	 ('Consejo Nacional para el VIH y el SIDA'),
	 ('Consejo Nacional para la Niñez y la Adolescencia'),
	 ('Consejo Nacional para la Reglamentación y Fomento de la Industria Lechera'),
	 ('Consejo Nacional para la Soberanía y Seguridad Alimentaria y Nutricional'),
	 ('Consejo Nacional para las Comunidades Dominicanas en el Exterior'),
	 ('Consejo para la Innovación y Desarrollo Tecnológico'),
	 ('Consejo para la Seguridad Alimentaria'),
	 ('Consejo Presidencial del Sida');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Consejo Provincial para la Administración de los Fondos Mineros Sánchez Ramírez'),
	 ('Consejo Superior de Administración Tributaria'),
	 ('Consultoría de Cooperación'),
	 ('Consultoría Jurídica del Poder Ejecutivo'),
	 ('Contraloría General de la República'),
	 ('Corporación de Fomento de la Industria Hotelera y Desarrollo del Turismo'),
	 ('Corporación del Acueducto y Alcantarillado de Boca Chica'),
	 ('Corporación del Acueducto y Alcantarillado de la Provincia Duarte'),
	 ('Corporación del Acueducto y Alcantarillado de la Provincia Monseñor Nouel'),
	 ('Corporación del Acueducto y Alcantarillado de la Romana');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Corporación del Acueducto y Alcantarillado de La Vega'),
	 ('Corporación del Acueducto y Alcantarillado de Moca'),
	 ('Corporación del Acueducto y Alcantarillado de Puerto Plata'),
	 ('Corporación del Acueducto y Alcantarillado de Santiago'),
	 ('Corporación del Acueducto y Alcantarillado de Santo Domingo'),
	 ('Corporación Dominicana de Empresas Eléctricas Estatales'),
	 ('Corporación Estatal de Radio y Televisión'),
	 ('Cruz Roja Dominicana'),
	 ('Cuerpo de Bomberos de Boca Chica'),
	 ('Cuerpo de Bomberos de la República Dominicana');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Cuerpo de Bomberos de Los Alcarrizos'),
	 ('Cuerpo de Bomberos de Pedro Brand'),
	 ('Cuerpo de Bomberos Santo Domingo'),
	 ('Cuerpo de Bomberos Santo Domingo Este'),
	 ('Cuerpo de Bomberos Santo Domingo Norte'),
	 ('Cuerpo de Bomberos Santo Domingo Oeste'),
	 ('Cuerpo de Seguridad Presidencial'),
	 ('Cuerpo Especializado de Control de Combustibles'),
	 ('Cuerpo Especializado de Seguridad Aeroportuaria y de la Aviación Civil'),
	 ('Cuerpo Especializado de Seguridad de las Instituciones del Estado y Funcionarios Públicos');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Cuerpo Especializado de Seguridad Fronteriza Terrestre'),
	 ('Cuerpo Especializado de Seguridad Portuaria'),
	 ('Cuerpo Especializado de Seguridad Turística'),
	 ('Cuerpo Especializado para la Seguridad del Metro de Santo Domingo'),
	 ('Defensor del Pueblo'),
	 ('Departamento Aeroportuario'),
	 ('Departamento Nacional de Investigaciones'),
	 ('Desarrollo Territorial y de Comunidades (Proyecto La Barquita)'),
	 ('Despacho de la Primera Dama'),
	 ('DGA Adm Haina Oriental');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('DGA Adm. AILA Pasajero'),
	 ('DGA Adm. Boca Chica'),
	 ('DGA Adm. Puerto Multimodal Caucedo'),
	 ('DGA Adm. Santo Domingo'),
	 ('DGA Aeropuerto Joaquín Balaguer'),
	 ('DGA Aeropuerto José F. Peña G'),
	 ('Dirección Administrativa y Financiera de la Policía Nacional'),
	 ('Dirección Central Antinarcoticos (DICAN) de la Policía Nacional'),
	 ('Dirección Central Cuerpo Médico y Sanidad Policial de la Policía Nacional'),
	 ('Dirección Central de Antipandillas de la Policía Nacional');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección Central de Asuntos Internos (DICAI) de la Policía Nacional'),
	 ('Dirección Central de Asuntos Legales de la Policía Nacional'),
	 ('Dirección Central de Entrenamiento Policial de la Policía Nacional'),
	 ('Dirección Central de Información y Relaciones Publicas de la Policía Nacional'),
	 ('Dirección Central de Inteligencia Delictiva (DINTEL) de la Policía Nacional'),
	 ('Dirección Central de Investigaciones Criminales (DICRIM) de la Policía Nacional'),
	 ('Dirección Central de Prevención de la Policía Nacional'),
	 ('Dirección Central de Recursos Humanos de la Policía Nacional'),
	 ('Dirección Central de Soporte y Servicios de la Policía Nacional'),
	 ('Dirección Central Especializada de Seguridad del Metro de Santo Domingo de la Policía Nacional');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección Central Especializada Niños(as) Adolecentes de la Policía Nacional'),
	 ('Dirección Central Especializada Prot. a la Mujer y Violencia Intrafamiliar de la Policía Nacional'),
	 ('Dirección Central Operaciones Policiales de la Policía Nacional'),
	 ('Dirección Central Policía Auxiliar de la Policía Nacional'),
	 ('Dirección Central Protección de Seguridad Judicial de la Policía Nacional'),
	 ('Dirección Central Protección de Servicios Especializados de la Policía Nacional'),
	 ('Dirección Central Protección Seguridad Escolar de la Policía Nacional'),
	 ('Dirección de Asuntos Internacionales de la Policía Nacional'),
	 ('Dirección de Comunicaciones (INTRANT)'),
	 ('Dirección de Comunicaciones Estratégicas de la Policía Nacional');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección de Estrategia y Comunicación Gubernamental'),
	 ('Dirección de Fomento y Desarrollo de la Artesanía Nacional'),
	 ('Dirección de Información'),
	 ('Dirección de Inteligencia del Estado Mayor Conjunto del Ministerio de las Fuerzas Armadas'),
	 ('Dirección de la Policía Comunitaria (Poliscom) de la Policía Nacional'),
	 ('Dirección de Movilidad Sostenible (INTRANT)'),
	 ('Dirección de Planificación Estrategica y Desarrollo de la Policía Nacional'),
	 ('Dirección de Prensa del Presidente de la República'),
	 ('Dirección de Protección al Consumidor Minorista'),
	 ('Dirección de Recursos Humanos (INTRANT)');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección de Reservas de la Policía Nacional'),
	 ('Dirección de Tecnología de la Información (INTRANT)'),
	 ('Dirección de Telemática de la Policía Nacional'),
	 ('Dirección del Comité de Retiro de la Policía Nacional'),
	 ('Dirección del Museo Policial de la Policía Nacional'),
	 ('Dirección Ejecutiva de la Reforma Policial de la Policía Nacional'),
	 ('Dirección Ejecutiva del Patronato La Nueva Barquita'),
	 ('Dirección Ejecutiva del Sistema Nacional de Atención a Emergencias y Seguridad 9-1-1'),
	 (''),
	 ('Dirección General Administrativa Financiera');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección General de Aduanas'),
	 ('Dirección General de Albergues y Residencias de las FF.AA para la Reeducación de Niños'),
	 ('Dirección General de Alianzas Público Privadas'),
	 ('Dirección General de Análisis y Política Fiscal'),
	 ('Dirección General de Bellas Artes'),
	 ('Dirección General de Bienes Nacionales'),
	 ('Dirección General de Catastro Nacional'),
	 ('Dirección General de Cine'),
	 ('Dirección General de Comunidad Digna'),
	 ('Dirección General de Contabilidad Gubernamental');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección General de Contrataciones Públicas'),
	 ('Dirección General de Control'),
	 ('Dirección General de Cooperación Bilateral'),
	 ('Dirección General de Cooperación Multilateral'),
	 ('Dirección General de Crédito Público'),
	 ('Dirección General de Currículo'),
	 ('Dirección General de Desarrollo de la Comunidad'),
	 ('Dirección General de Desarrollo Económico y Social'),
	 ('Dirección General de Desarrollo Fronterizo'),
	 ('Dirección General de Dragas');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección General de Edificaciones'),
	 ('Dirección General de Educación Básica'),
	 ('Dirección General de Educación Inicial'),
	 ('Dirección General de Educación Media'),
	 ('Dirección General de Educación para Jóvenes y Adultos'),
	 ('Dirección General de Embellecimiento de Carreteras y Avenidas de Circunvalación del País'),
	 ('Dirección General de Empleo'),
	 ('Dirección General de Escuelas de Graduados de Estudios Superiores'),
	 ('Dirección General de Escuelas Vocacionales'),
	 ('Dirección General de Estudios');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección General de Ética e Integridad Gubernamental'),
	 ('Dirección General de Formación y Capacitación'),
	 ('Dirección General de Ganadería'),
	 ('Dirección General de Higiene y Seguridad Industrial'),
	 ('Dirección General de Historia Militar'),
	 ('Dirección General de Impuestos Internos'),
	 ('Dirección General de Información y Defensa de los Afiliados a la Seguridad Social'),
	 ('Dirección General de Ingeniería'),
	 ('Dirección General de Inversión Pública'),
	 ('Dirección General de Jubilaciones y Pensiones a Cargo del Estado');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Direccion General de la Industria Militar de las Fuerzas Armadas'),
	 ('Dirección General de la Policía de Turismo'),
	 ('Dirección General de la Policía Nacional'),
	 ('Dirección General de la Reserva de las Fuerzas Armadas y la Policía'),
	 ('Dirección General de las Reservas de las Fuerzas Armadas'),
	 ('Dirección General de Mecenazgo'),
	 ('Dirección General de Medicamentos'),
	 ('Dirección General de Migración'),
	 ('Dirección General de Minería'),
	 ('Dirección General de Museos');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección General de Operaciones y Mantenimiento Vial'),
	 ('Dirección General de Ordenamiento y Desarrollo Territorial'),
	 ('Dirección General de Pasaportes'),
	 ('Dirección General de Pasaportes Regional Santiago'),
	 ('Dirección General de Persecución del Ministerio Público'),
	 ('Dirección General de Planificación y Desarrollo'),
	 ('Dirección General de Política y Legislación Tributaria'),
	 ('Dirección General de Presupuesto'),
	 ('Dirección General de Prisiones'),
	 ('Dirección General de Promoción de las Comunidades Fronterizas');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección General de Proyectos Estratégicos y Especiales de la Presidencia'),
	 ('Dirección General de Reglamentos y Sistemas'),
	 ('Dirección General de Riesgos Agropecuarios'),
	 ('Dirección General de Seguridad de Tránsito y Transporte Terrestre'),
	 ('Dirección General de Supervisión y Fiscalización de Obras'),
	 ('Dirección General de Trabajo'),
	 ('Dirección General de Tránsito Terrestre'),
	 ('Dirección General del Libro y la Lectura'),
	 ('Dirección General del Plan Social de las Fuerzas Armadas'),
	 ('Dirección General Radiodifusora Cultural La Voz de las Fuerzas Armadas');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección Jurídica (INTRANT)'),
	 ('Dirección Nacional de Atención Integral de la Persona Adolescente en Conflicto con la Ley Penal'),
	 ('Dirección Nacional de Control de Drogas'),
	 ('Dirección Nacional de Mensuras Catastrales'),
	 ('Dirección Nacional de Registro de Títulos'),
	 ('Dirección Nacional de Seguridad Preventiva de la Policía Nacional'),
	 ('Dirección Policial de Protección de Dignatarios'),
	 ('Dirección Provincial de Salud (DPS) – Azua'),
	 ('Dirección Provincial de Salud (DPS) – Bahoruco'),
	 ('Dirección Provincial de Salud (DPS) – Barahona');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección Provincial de Salud (DPS) – Dajabón'),
	 ('Dirección Provincial de Salud (DPS) – Duarte'),
	 ('Dirección Provincial de Salud (DPS) – El Seibo'),
	 ('Dirección Provincial de Salud (DPS) – Elías Piña'),
	 ('Dirección Provincial de Salud (DPS) – Espaillat'),
	 ('Dirección Provincial de Salud (DPS) – Hato Mayor'),
	 ('Dirección Provincial de Salud (DPS) – Hermanas Mirabal'),
	 ('Dirección Provincial de Salud (DPS) – Independencia'),
	 ('Dirección Provincial de Salud (DPS) – La Altagracia'),
	 ('Dirección Provincial de Salud (DPS) – La Romana');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección Provincial de Salud (DPS) – La Vega'),
	 ('Dirección Provincial de Salud (DPS) – María Trinidad Sánchez'),
	 ('Dirección Provincial de Salud (DPS) – Monseñor Nouel'),
	 ('Dirección Provincial de Salud (DPS) – Monte Cristi'),
	 ('Dirección Provincial de Salud (DPS) – Monte Plata'),
	 ('Dirección Provincial de Salud (DPS) – Pedernales'),
	 ('Dirección Provincial de Salud (DPS) – Peravia'),
	 ('Dirección Provincial de Salud (DPS) – Puerto Plata'),
	 ('Dirección Provincial de Salud (DPS) – Samaná'),
	 ('Dirección Provincial de Salud (DPS) – San Cristóbal');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección Provincial de Salud (DPS) – San José de Ocoa'),
	 ('Dirección Provincial de Salud (DPS) – San Juan de la Maguana'),
	 ('Dirección Provincial de Salud (DPS) – San Pedro de Macorís'),
	 ('Dirección Provincial de Salud (DPS) – Sánchez Ramírez'),
	 ('Dirección Provincial de Salud (DPS) – Santiago I'),
	 ('Dirección Provincial de Salud (DPS) – Santiago II'),
	 ('Dirección Provincial de Salud (DPS) – Santiago III'),
	 ('Dirección Provincial de Salud (DPS) – Santiago Rodríguez'),
	 ('Dirección Provincial de Salud (DPS) – Valverde'),
	 ('Dirección Regional Central del Distrito Nacional de la Policía Nacional');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección Regional Cibao Central (Santiago) de la Policía Nacional'),
	 ('Dirección Regional Cibao Sur (Bonao) de la Policía Nacional'),
	 ('Dirección Regional de Educación 06 La Vega'),
	 ('Dirección Regional de Educación no.17 (Monte Plata)'),
	 ('Dirección Regional Este (La Romana) de la Policía Nacional'),
	 ('Dirección Regional Noroeste (Mao) de la Policía Nacional'),
	 ('Dirección Regional Noroeste (San Fco. de Macorís) de la Policía Nacional'),
	 ('Dirección Regional Norte (Puerto Plata) de la Policía Nacional'),
	 ('Dirección Regional Oeste (San Juan de la Maguana) de la Policía Nacional'),
	 ('Dirección Regional Santo Domingo Norte (Villa Mella) de la Policía Nacional');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Dirección Regional Santo Domingo Oeste (Los Alcarrizos) de la Policía Nacional'),
	 ('Dirección Regional Santo Domingo Oriental (Invivienda) de la Policía Nacional'),
	 ('Dirección Regional Sur (Barahona) de la Policía Nacional'),
	 ('Dirección Regional Sur Central (Bani) de la Policía Nacional'),
	 ('Dirección Regional Sureste (San Pedro de Macorís) de la Policía Nacional'),
	 ('Dirección Remediación Ambiental Mina Pueblo Viejo'),
	 ('Distrito Educativo 04-01 Cambita'),
	 ('Distrito Educativo 04-03 San Cristóbal Sur'),
	 ('Distrito Educativo 06-04 La Vega Oeste'),
	 ('Distrito Educativo 06-05 La Vega Este');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Distrito Educativo 08 06'),
	 ('Distrito Educativo 08 08 Licey Al Medio'),
	 ('Distrito Educativo 08-09 Tamboril'),
	 ('Distrito Educativo 10-04 Alma Rosa I'),
	 ('Distrito Educativo 15-01 Los Alcarrizos'),
	 ('Distrito Educativo 17-04 Sabana Grande de Boya'),
	 ('Distrito Educativo 17-05 Peralvillo'),
	 ('Empresa de Generación Hidroeléctrica Dominicana'),
	 ('Empresa de Transmisión Eléctrica Dominicana'),
	 ('Empresa Distribuidora de Electricidad del Este');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Empresa Distribuidora de Electricidad del Norte'),
	 ('Empresa Distribuidora de Electricidad del Sur'),
	 ('Escuela de Graduados de Educación Superior “Juan Pablo Duarte y Diez”'),
	 ('Escuela Experimental Luis Napoleón Núñez Molina'),
	 ('Escuela Nacional Penitenciaria'),
	 ('Escuelas Vocacionales de las Fuerzas Armadas y la Policía Nacional'),
	 ('Fiscalía del Distrito Judicial del Distrito Nacional'),
	 ('Fomento y Producción Cunaria'),
	 ('Fondo de Desarrollo del Transporte Terrestre'),
	 ('Fondo de Pensiones y Jubilaciones de los Trabajadores de la Construcción');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Fondo de Pensiones y Jubilaciones de los Trabajadores Portuarios'),
	 ('Fondo de Promocion a las Iniciativas Comunitarias'),
	 ('Fondo Especial para el Desarrollo Agropecuario'),
	 ('Fondo Nacional para el Medio Ambiente y Recursos Naturales'),
	 ('Fondo Patrimonial de las Empresas Reformadas'),
	 ('Gabinete de Coordinación de la Política Económica'),
	 ('Gabinete de Coordinación de Política Institucional'),
	 ('Gabinete de Coordinación de Política Medioambiental y Desarrollo Físico'),
	 ('Gabinete de Coordinación de Política Social'),
	 ('Gabinete de Educación y Cultura');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Gabinete de la Familia'),
	 ('Gabinete de Promoción de Inversiones'),
	 ('Gabinete de Salud'),
	 ('Gabinete de Turismo'),
	 ('Gabinete del Sector Agua'),
	 ('Gabinete del Sector Construcción'),
	 ('Gabinete del Sector Eléctrico'),
	 ('Gabinete Económico'),
	 ('Gabinete Social de la República Dominicana'),
	 ('Gerencia de Área de Red de Salud I Servicio Regional de Salud El Valle');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Gobernación de las Oficinas Gubernamentales Prof. Juan Bosch'),
	 ('Gobernación de Oficina Gubernamentales'),
	 ('Gobernación Edificio de Oficinas Gubernamentales Juan Pablo Duarte'),
	 ('Hospital Central de la Policía Nacional'),
	 ('Hospital Central de las Fuerzas Armadas'),
	 ('Hospital Ciudad Juan Bosch de Santo Domingo Este'),
	 ('Hospital Docente Padre Billini'),
	 ('Hospital Docente SEMMA de Santiago'),
	 ('Hospital Docente SEMMA de Santo Domingo'),
	 ('Hospital Docente Universitario Dr. Darío Contreras');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Dr. Alejo Martinez Garcia'),
	 ('Hospital Dr. Angel Concepción Lajara'),
	 ('Hospital Dr. Antonio Yapor Hedded'),
	 ('Hospital Dr. Arístides Fiallo Cabral'),
	 ('Hospital Dr. Carlos Alberto Zafra'),
	 ('Hospital Dr. Federico Leopoldo Lavandier'),
	 ('Hospital Dr. Francisco Antonio Gonzalvo'),
	 ('Hospital Dr. Francisco E. Moscoso Puello'),
	 ('Hospital Dr. Jaime Oliver Pino'),
	 ('Hospital Dr. Jaime Sánchez');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Dr. Juan Antonio Castillo'),
	 ('Hospital Dr. Pedro Emilio de Marchena'),
	 ('Hospital Dr. Rafael J. Mañón'),
	 ('Hospital Dr. Rodolfo de la Cruz Lora'),
	 ('Hospital Dr. Román Brache'),
	 ('Hospital Dr. Salvador B. Gautier de Santo Domingo'),
	 ('Hospital Dr. Sigifredo Alba Domínguez'),
	 ('Hospital Dr. Teófilo Hernández'),
	 ('Hospital Dr. Toribio Bencosme'),
	 ('Hospital Dra. Armida García');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Dra. Evangelina Rodríguez'),
	 ('Hospital Felipe Javier Achecar'),
	 ('Hospital General Dr. Vinicio Calventi'),
	 ('Hospital General Provincial Santiago Rodríguez'),
	 ('Hospital General Regional Dr. Marcelino Vélez Santana'),
	 ('Hospital General y de Especialidades Nuestra Señora de La Altagracia'),
	 ('Hospital Infantil Dr. Robert Reid Cabral'),
	 ('Hospital Infantil Regional Dr. Arturo Grullón'),
	 ('Hospital Inmaculada Concepción'),
	 ('Hospital Juan Pablo Pina');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Julia Santana de Tamayo'),
	 ('Hospital Leprocomio Ntra. Sra. De Las Mercedes'),
	 ('Hospital Local Boca Chica'),
	 ('Hospital Maternidad Nuestra Señora de la Altagracia'),
	 ('Hospital Materno Dr. Reynaldo Almánzar'),
	 ('Hospital Materno Infantil Dr. Francisco Peña Gómez'),
	 ('Hospital Materno Infantil San Lorenzo de Los Mina'),
	 ('Hospital Materno Infantil Santo Socorro'),
	 ('Hospital Municipal Alcarrizos II'),
	 ('Hospital Municipal Alicia de Legendre de Villa Rivas');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Municipal Antonio Fernández'),
	 ('Hospital Municipal Arenoso'),
	 ('Hospital Municipal Bajos de Haina'),
	 ('Hospital Municipal Cambita Pueblo'),
	 ('Hospital Municipal Consuelo Dr. Ángel Ponce'),
	 ('Hospital Municipal de Altamira – Puerto Plata'),
	 ('Hospital Municipal de Bánica'),
	 ('Hospital Municipal de Bohechio'),
	 ('Hospital Municipal de Cabral'),
	 ('Hospital Municipal de Castañuelas');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Municipal de Castillo'),
	 ('Hospital Municipal de Cevicos'),
	 ('Hospital Municipal de Engombe'),
	 ('Hospital Municipal de Esperanza Dr. José Fausto Ovalles'),
	 ('Hospital Municipal de Guayabal'),
	 ('Hospital Municipal de Haina'),
	 ('Hospital Municipal de Imbert'),
	 ('Hospital Municipal de las Guaranas Dra. Etanilda Brito'),
	 ('Hospital Municipal de Licey al Medio'),
	 ('Hospital Municipal de Monción');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Municipal de Navarrete'),
	 ('Hospital Municipal de Pepillo Salcedo'),
	 ('Hospital Municipal de Peralta'),
	 ('Hospital Municipal de Tamboril Dr. Jorge Armando Ico'),
	 ('Hospital Municipal de Vallejuelo'),
	 ('Hospital Municipal de Villa Altagracia'),
	 ('Hospital Municipal de Yaguate'),
	 ('Hospital Municipal del Cercado'),
	 ('Hospital Municipal del Partido'),
	 ('Hospital Municipal Dr. Alberto Gautreaux');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Municipal Dr. Alfredo González Gil Roldan'),
	 ('Hospital Municipal Dr. Federico A. Aybar'),
	 ('Hospital Municipal Dr. Guarionex Alcántara'),
	 ('Hospital Municipal Dr. Jorge Armando Martínez'),
	 ('Hospital Municipal Dr. José Pérez'),
	 ('Hospital Municipal Dr. Luis Espaillat de Sabana Iglesia'),
	 ('Hospital Municipal Dr. Mario Fernández Mena'),
	 ('Hospital Municipal Dr. Napier Díaz'),
	 ('Hospital Municipal Dr. Pedro Heredia Rojas Giovanni'),
	 ('Hospital Municipal Dr. Virgilio García');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Municipal Dra. Evangelina Rodriguez Perozo'),
	 ('Hospital Municipal El Almirante'),
	 ('Hospital Municipal el Valle – Hato Mayor'),
	 ('Hospital Municipal Félix María Goico'),
	 ('Hospital Municipal Guananico'),
	 ('Hospital Municipal Guayubín'),
	 ('Hospital Municipal Hato del Yaque de Santiago'),
	 ('Hospital Municipal Hondo Valle'),
	 ('Hospital Municipal Jacinto Ignacio Mañon'),
	 ('Hospital Municipal Jamao al Norte');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Municipal José de Jesús Jiménez Almonte'),
	 ('Hospital Municipal Juan de Herrera'),
	 ('Hospital Municipal Laguna Salada'),
	 ('Hospital Municipal Las Matas de Santa Cruz'),
	 ('Hospital Municipal Los Ríos- De Bahoruco'),
	 ('Hospital Municipal Mata Hambre'),
	 ('Hospital Municipal Materno Infantil Dr. Luís Bonilla Castillo'),
	 ('Hospital Municipal Materno Infantil Villa Mella'),
	 ('Hospital Municipal Nuestra Señora del Carmen Padres Las Casa'),
	 ('Hospital Municipal Nuestra Sra. De La Altagracia (VILLA ALTAGRACIA)');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Municipal Pablo Antonio Paulino'),
	 ('Hospital Municipal Pablo Morrobel Jiménez'),
	 ('Hospital Municipal Restauración'),
	 ('Hospital Municipal Roman Bautista Brache'),
	 ('Hospital Municipal San José de las Matas'),
	 ('Hospital Municipal Señorita Elupina Cordero'),
	 ('Hospital Municipal Villa Fundación'),
	 ('Hospital Municipal Villa Tapia'),
	 ('Hospital Nuestra Señora de Regla'),
	 ('Hospital Padre Fantino');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Pascasio Toribio'),
	 ('Hospital Pediátrico Dr. Hugo Mendoza'),
	 ('Hospital Periférico Dr. Rafael Castro'),
	 ('Hospital Periférico Ensanche Libertad'),
	 ('Hospital Periferico Monte Adentro Dr. Antonio Trueba'),
	 ('Hospital Presidente Estrella Ureña'),
	 ('Hospital Provincial Dr. Ángel Ramón Contreras Mejía'),
	 ('Hospital Provincial Dr. Elio Fiallo'),
	 ('Hospital Provincial Dr. Leopoldo Martínez'),
	 ('Hospital Provincial Dr. Leopoldo Pou');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Provincial General Melenciano'),
	 ('Hospital Provincial Leopoldo Pou'),
	 ('Hospital Provincial Materno Infantil Nuestra Señora de la Altagracia'),
	 ('Hospital Provincial Matías Ramón Mella'),
	 ('Hospital Provincial Rosa Duarte'),
	 ('Hospital Provincial San Bartolomé'),
	 ('Hospital Ramón de Lara'),
	 ('Hospital Regional Dr. Alejandro Cabral'),
	 ('Hospital Regional Dr. Antonio Musa'),
	 ('Hospital Regional Dr. Luís Morillo King');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Hospital Regional Ing. Luis L. Bogaert'),
	 ('Hospital Regional Jaime Mota'),
	 ('Hospital Regional San Vicente de Paul'),
	 ('Hospital Regional Taiwán 19 de Marzo'),
	 ('Hospital Regional Universitario José María Cabral y Báez'),
	 ('Hospital Ricardo Limardo'),
	 ('Hospital San José'),
	 ('Hospital Traumatológico Dr. Ney Arias Lora'),
	 ('Hospital Traumatológico y Quirúrgico Prof. Juan Bosch'),
	 ('Hospital Yrene Fernández Jánico');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Industria Nacional de la Aguja'),
	 ('Inspectoría General de la Policía Nacional'),
	 ('Instituto Agrario Dominicano'),
	 ('Instituto Azucarero Dominicano'),
	 ('Instituto Cartográfico Militar'),
	 ('Instituto de Altos Estudios para la Defensa y Seguridad Nacional (Escuela de Graduados de Altos Estudios Estratégicos)'),
	 ('Instituto de Auxilios y Viviendas'),
	 ('Instituto de Desarrollo y Crédito Cooperativo'),
	 ('Instituto de Dignidad Humana de la Policía Nacional'),
	 ('Instituto de Dominicanos y Dominicanas en el Exterior');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Instituto de Educación Superior en Formación Diplomática y Consular “Dr. Eduardo Latorre Rodríguez”'),
	 ('Instituto de Educación Superior Escuela Nacional del Ministerio Público'),
	 ('Instituto de Estabilización de Precios'),
	 ('Instituto de Estudios Superiores (IPES) de la Policía Nacional'),
	 ('Instituto de Formación Turística del Caribe'),
	 ('Instituto de Innovación en Biotecnología e Industria'),
	 ('Instituto de Seguridad Social de la Policía Nacional'),
	 ('Instituto de Seguridad Social de las Fuerzas Armadas'),
	 ('Instituto del Tabaco de la República Dominicana'),
	 ('Instituto Dominicano de Aviación Civil');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Instituto Dominicano de Evaluación e Investigación de la Calidad Educativa'),
	 ('Instituto Dominicano de Investigaciones Agropecuarias y Forestales'),
	 ('Instituto Dominicano de las Telecomunicaciones'),
	 ('Instituto Dominicano de Prevención y Protección de Riesgos Laborales'),
	 ('Instituto Dominicano de Seguros Sociales'),
	 ('Instituto Dominicano del Café'),
	 ('Instituto Dominicano para la Calidad'),
	 ('Instituto Duartiano'),
	 ('Instituto Especializado de Estudios Superiores de la Policia Nacional'),
	 ('Instituto Geográfico Nacional José Joaquín Hungría Morell');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Instituto Militar de los Derechos Humanos y Derecho Internacional Humanitario'),
	 ('Instituto Nacional de Administración Pública'),
	 ('Instituto Nacional de Aguas Potables y Alcantarillados'),
	 ('Instituto Nacional de Atención Integral a la Primera Infancia'),
	 ('Instituto Nacional de Bienestar Estudiantil'),
	 ('Instituto Nacional de Bienestar Magisterial'),
	 ('Instituto Nacional de Ciencias Forenses'),
	 ('Instituto Nacional de Coordinación de Trasplante'),
	 ('Instituto Nacional de Educación Física'),
	 ('Instituto Nacional de Formación Técnico Profesional');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Instituto Nacional de Formación Técnico Profesional Oficina Nacional'),
	 ('Instituto Nacional de Formación Técnico Profesional Regional Este'),
	 ('Instituto Nacional de Formación Técnico Profesional Regional Gerencia Central'),
	 ('Instituto Nacional de Formación Técnico Profesional Regional Norte'),
	 ('Instituto Nacional de Formación Técnico Profesional Regional Sur'),
	 ('Instituto Nacional de Formación y Capacitación del Magisterio'),
	 ('Instituto Nacional de la Uva'),
	 ('Instituto Nacional de Migración'),
	 ('Instituto Nacional de Patología Forense'),
	 ('Instituto Nacional de Protección de los Derechos del Consumidor');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Instituto Nacional de Recursos Hidráulicos'),
	 ('Instituto Nacional de Tránsito y Transporte Terrestre'),
	 ('Instituto Nacional del Cáncer Rosa Emilia Tavárez'),
	 ('Instituto para el Desarrollo del Noroeste'),
	 ('Instituto para el Desarrollo del Suroeste'),
	 ('Instituto Policial de Educación'),
	 ('Instituto Postal Dominicano'),
	 ('Instituto Superior de Formación Docente Salomé Ureña'),
	 ('Instituto Superior para la Defensa'),
	 ('Instituto Técnico Superior Comunitario');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Instituto Tecnológico de las Américas'),
	 ('Intendencia General de la Policía Nacional'),
	 ('Jardín Botánico de Santiago “Prof. Eugenio de Jesús Marcano Fondeur”'),
	 ('Jardín Botánico Nacional “Dr. Rafael M. Moscoso”'),
	 ('Jefatura de la Policía Nacional'),
	 ('Junta Central Electoral'),
	 ('Junta de Aviación Civil'),
	 ('Junta de Distrito Municipal de Agua Santa del Yuna'),
	 ('Junta de Distrito Municipal de Aguacate'),
	 ('Junta de Distrito Municipal de Amiama Gómez');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Ámina'),
	 ('Junta de Distrito Municipal de Angelina'),
	 ('Junta de Distrito Municipal de Arroyo al Medio'),
	 ('Junta de Distrito Municipal de Arroyo Barril'),
	 ('Junta de Distrito Municipal de Arroyo Cano'),
	 ('Junta de Distrito Municipal de Arroyo Dulce'),
	 ('Junta de Distrito Municipal de Arroyo Salado'),
	 ('Junta de Distrito Municipal de Arroyo Toro – Masipedro'),
	 ('Junta de Distrito Municipal de Bahoruco'),
	 ('Junta de Distrito Municipal de Barraquito');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Barreras'),
	 ('Junta de Distrito Municipal de Barro Arriba'),
	 ('Junta de Distrito Municipal de Batey 8'),
	 ('Junta de Distrito Municipal de Batista'),
	 ('Junta de Distrito Municipal de Bayahibe'),
	 ('Junta de Distrito Municipal de Belloso'),
	 ('Junta de Distrito Municipal de Blanco'),
	 ('Junta de Distrito Municipal de Boca de Cachón'),
	 ('Junta de Distrito Municipal de Boca de Mao'),
	 ('Junta de Distrito Municipal de Boca de Yuma');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Boyá'),
	 ('Junta de Distrito Municipal de Buena Vista'),
	 ('Junta de Distrito Municipal de Caballero'),
	 ('Junta de Distrito Municipal de Cabarete'),
	 ('Junta de Distrito Municipal de Cabeza de Toro'),
	 ('Junta de Distrito Municipal de Caleta'),
	 ('Junta de Distrito Municipal de Cambita El Pueblecito'),
	 ('Junta de Distrito Municipal de Cana Chapetón'),
	 ('Junta de Distrito Municipal de Canabacoa'),
	 ('Junta de Distrito Municipal de Canca La Piedra');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Canca la Reina'),
	 ('Junta de Distrito Municipal de Canoa'),
	 ('Junta de Distrito Municipal de Cañongo'),
	 ('Junta de Distrito Municipal de Capotillo'),
	 ('Junta de Distrito Municipal de Carrera de Yegua'),
	 ('Junta de Distrito Municipal de Catalina'),
	 ('Junta de Distrito Municipal de Cenoví'),
	 ('Junta de Distrito Municipal de Chirino'),
	 ('Junta de Distrito Municipal de Clavellina'),
	 ('Junta de Distrito Municipal de Comedero Arriba');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Cristo Rey de Guaraguao'),
	 ('Junta de Distrito Municipal de Cruce de Guayacanes'),
	 ('Junta de Distrito Municipal de Cumayasa'),
	 ('Junta de Distrito Municipal de Don Juan'),
	 ('Junta de Distrito Municipal de Don Juan Rodriguez'),
	 ('Junta de Distrito Municipal de Doña Ana'),
	 ('Junta de Distrito Municipal de El Cachón'),
	 ('Junta de Distrito Municipal de El Caimito'),
	 ('Junta de Distrito Municipal de El Carretón'),
	 ('Junta de Distrito Municipal de El Carril');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de El Cedro'),
	 ('Junta de Distrito Municipal de El Higüerito'),
	 ('Junta de Distrito Municipal de El Limón – Jimaní'),
	 ('Junta de Distrito Municipal de El Limón – Samaná'),
	 ('Junta de Distrito Municipal de El Limón – Villa González'),
	 ('Junta de Distrito Municipal de El Limonal'),
	 ('Junta de Distrito Municipal de El Naranjal'),
	 ('Junta de Distrito Municipal de El Palmar'),
	 ('Junta de Distrito Municipal de El Pinar'),
	 ('Junta de Distrito Municipal de El Pozo');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de El Puerto'),
	 ('Junta de Distrito Municipal de El Ranchito'),
	 ('Junta de Distrito Municipal de El Rosario – Pueblo Viejo'),
	 ('Junta de Distrito Municipal de El Rosario – San Juan de la Maguana'),
	 ('Junta de Distrito Municipal de El Rubio'),
	 ('Junta de Distrito Municipal de El Salado'),
	 ('Junta de Distrito Municipal de Elupina Cordero de Las Cañitas'),
	 ('Junta de Distrito Municipal de Emma Balaguer Vda. Vallejo'),
	 ('Junta de Distrito Municipal de Estero Hondo'),
	 ('Junta de Distrito Municipal de Estrecho');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Fondo Negro'),
	 ('Junta de Distrito Municipal de Ganadero'),
	 ('Junta de Distrito Municipal de Gautier'),
	 ('Junta de Distrito Municipal de Gonzalo'),
	 ('Junta de Distrito Municipal de Gualete'),
	 ('Junta de Distrito Municipal de Guanito – El Llano'),
	 ('Junta de Distrito Municipal de Guanito – San Juan de La Maguana'),
	 ('Junta de Distrito Municipal de Guatapanal'),
	 ('Junta de Distrito Municipal de Guayabal – Postrer Río'),
	 ('Junta de Distrito Municipal de Guayabal – Puñal');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Guayabo'),
	 ('Junta de Distrito Municipal de Guayabo Dulce'),
	 ('Junta de Distrito Municipal de Hatillo'),
	 ('Junta de Distrito Municipal de Hatillo Palma'),
	 ('Junta de Distrito Municipal de Hato Damas'),
	 ('Junta de Distrito Municipal de Hato del Padre'),
	 ('Junta de Distrito Municipal de Hato del Yaque'),
	 ('Junta de Distrito Municipal de Hato Nuevo – Cortés'),
	 ('Junta de Distrito Municipal de Hato Nuevo – San Juan de la Maguana'),
	 ('Junta de Distrito Municipal de Hato Viejo');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Hernando Alonzo'),
	 ('Junta de Distrito Municipal de Jaibón – Laguna Salada'),
	 ('Junta de Distrito Municipal de Jaibón (Pueblo Nuevo)'),
	 ('Junta de Distrito Municipal de Jamao Afuera'),
	 ('Junta de Distrito Municipal de Jaya'),
	 ('Junta de Distrito Municipal de Jayaco'),
	 ('Junta de Distrito Municipal de Jicomé'),
	 ('Junta de Distrito Municipal de Jínova'),
	 ('Junta de Distrito Municipal de Joba Arriba'),
	 ('Junta de Distrito Municipal de Jorjillo');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de José Contreras'),
	 ('Junta de Distrito Municipal de José Francisco Peña Gómez'),
	 ('Junta de Distrito Municipal de Juan Adrián'),
	 ('Junta de Distrito Municipal de Juan López'),
	 ('Junta de Distrito Municipal de Juancho'),
	 ('Junta de Distrito Municipal de Juma Bejucal'),
	 ('Junta de Distrito Municipal de Juncalito'),
	 ('Junta de Distrito Municipal de La Bija'),
	 ('Junta de Distrito Municipal de La Caleta'),
	 ('Junta de Distrito Municipal de La Canela');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de La Caya'),
	 ('Junta de Distrito Municipal de La Ciénaga'),
	 ('Junta de Distrito Municipal de La Colonia'),
	 ('Junta de Distrito Municipal de La Cuaba'),
	 ('Junta de Distrito Municipal de La Cuchilla'),
	 ('Junta de Distrito Municipal de La Cuesta'),
	 ('Junta de Distrito Municipal de La Cueva'),
	 ('Junta de Distrito Municipal de La Entrada'),
	 ('Junta de Distrito Municipal de La Gina'),
	 ('Junta de Distrito Municipal de La Guáyiga');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de La Guázara'),
	 ('Junta de Distrito Municipal de La Isabela'),
	 ('Junta de Distrito Municipal de La Jagua'),
	 ('Junta de Distrito Municipal de La Jaiba'),
	 ('Junta de Distrito Municipal de La Ortega'),
	 ('Junta de Distrito Municipal de La Otra Banda'),
	 ('Junta de Distrito Municipal de La Peña'),
	 ('Junta de Distrito Municipal de La Sabina'),
	 ('Junta de Distrito Municipal de La Salvia – Los Quemados'),
	 ('Junta de Distrito Municipal de La Siembra');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de La Victoria'),
	 ('Junta de Distrito Municipal de Lagunas de Nisibón'),
	 ('Junta de Distrito Municipal de Las Barías – Baní'),
	 ('Junta de Distrito Municipal de Las Barías – La Estancia'),
	 ('Junta de Distrito Municipal de Las Charcas de María Nova'),
	 ('Junta de Distrito Municipal de Las Clavellinas'),
	 ('Junta de Distrito Municipal de Las Coles'),
	 ('Junta de Distrito Municipal de Las Galeras'),
	 ('Junta de Distrito Municipal de Las Gordas'),
	 ('Junta de Distrito Municipal de Las Lagunas – Moca');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Las Lagunas – Padre Las Casas'),
	 ('Junta de Distrito Municipal de Las Lomas'),
	 ('Junta de Distrito Municipal de Las Palomas'),
	 ('Junta de Distrito Municipal de Las Placetas'),
	 ('Junta de Distrito Municipal de Las Táranas'),
	 ('Junta de Distrito Municipal de Las Zanjas'),
	 ('Junta de Distrito Municipal de Los Botados'),
	 ('Junta de Distrito Municipal de Los Fríos'),
	 ('Junta de Distrito Municipal de Los Jovillos'),
	 ('Junta de Distrito Municipal de Los Patos');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Los Toros'),
	 ('Junta de Distrito Municipal de Maimón'),
	 ('Junta de Distrito Municipal de Maizal'),
	 ('Junta de Distrito Municipal de Majagual'),
	 ('Junta de Distrito Municipal de Mamá Tingó'),
	 ('Junta de Distrito Municipal de Manabao'),
	 ('Junta de Distrito Municipal de Manuel Bueno'),
	 ('Junta de Distrito Municipal de Mata Palacio'),
	 ('Junta de Distrito Municipal de Matayaya'),
	 ('Junta de Distrito Municipal de Medina');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Mena'),
	 ('Junta de Distrito Municipal de Monserrat'),
	 ('Junta de Distrito Municipal de Monte Bonito'),
	 ('Junta de Distrito Municipal de Monte de la Jagua'),
	 ('Junta de Distrito Municipal de Navas'),
	 ('Junta de Distrito Municipal de Nizao – Las Auyamas'),
	 ('Junta de Distrito Municipal de Nuevo Brasil'),
	 ('Junta de Distrito Municipal de Palmar Arriba'),
	 ('Junta de Distrito Municipal de Palmar de Ocoa'),
	 ('Junta de Distrito Municipal de Palmarejo – Villa Linda');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Palo Alto'),
	 ('Junta de Distrito Municipal de Palo Verde'),
	 ('Junta de Distrito Municipal de Pantoja'),
	 ('Junta de Distrito Municipal de Paradero'),
	 ('Junta de Distrito Municipal de Paya'),
	 ('Junta de Distrito Municipal de Pedro Corto'),
	 ('Junta de Distrito Municipal de Pedro García'),
	 ('Junta de Distrito Municipal de Pescadería'),
	 ('Junta de Distrito Municipal de Pizarrete'),
	 ('Junta de Distrito Municipal de Platanal');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Presidente Don Antonio Guzmán Fernández'),
	 ('Junta de Distrito Municipal de Proyecto 2-C'),
	 ('Junta de Distrito Municipal de Proyecto 4'),
	 ('Junta de Distrito Municipal de Puerto Viejo'),
	 ('Junta de Distrito Municipal de Quita Coraza'),
	 ('Junta de Distrito Municipal de Quita Sueño – Bajos de Haina'),
	 ('Junta de Distrito Municipal de Quita Sueño – Cotuí'),
	 ('Junta de Distrito Municipal de Rancho de La Guardia'),
	 ('Junta de Distrito Municipal de Rincón'),
	 ('Junta de Distrito Municipal de Río Grande');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Río Limpio'),
	 ('Junta de Distrito Municipal de Río Verde Arriba'),
	 ('Junta de Distrito Municipal de Sabana Alta'),
	 ('Junta de Distrito Municipal de Sabana Buey'),
	 ('Junta de Distrito Municipal de Sabana Cruz'),
	 ('Junta de Distrito Municipal de Sabana del Puerto'),
	 ('Junta de Distrito Municipal de Sabana Grande'),
	 ('Junta de Distrito Municipal de Sabana Higuero'),
	 ('Junta de Distrito Municipal de Sabana Larga'),
	 ('Junta de Distrito Municipal de Sabaneta');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Sabaneta de Yásica'),
	 ('Junta de Distrito Municipal de San Francisco – Vicentillo'),
	 ('Junta de Distrito Municipal de San Francisco de Jacagua'),
	 ('Junta de Distrito Municipal de San José de Matanzas'),
	 ('Junta de Distrito Municipal de San José del Puerto'),
	 ('Junta de Distrito Municipal de San Luis'),
	 ('Junta de Distrito Municipal de Santa Bárbara – El 6'),
	 ('Junta de Distrito Municipal de Santa Lucía'),
	 ('Junta de Distrito Municipal de Santa Maria'),
	 ('Junta de Distrito Municipal de Santana – Nizao');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Santana – Tamayo'),
	 ('Junta de Distrito Municipal de Santiago de la Cruz'),
	 ('Junta de Distrito Municipal de Santiago Oeste'),
	 ('Junta de Distrito Municipal de Tábara Abajo'),
	 ('Junta de Distrito Municipal de Tavera'),
	 ('Junta de Distrito Municipal de Tireo Arriba'),
	 ('Junta de Distrito Municipal de Uvilla'),
	 ('Junta de Distrito Municipal de Vengan a Ver'),
	 ('Junta de Distrito Municipal de Veragua'),
	 ('Junta de Distrito Municipal de Verón – Punta Cana');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Villa Central'),
	 ('Junta de Distrito Municipal de Villa de Pedro Sánchez'),
	 ('Junta de Distrito Municipal de Villa Elisa'),
	 ('Junta de Distrito Municipal de Villa Fundación'),
	 ('Junta de Distrito Municipal de Villa Magante'),
	 ('Junta de Distrito Municipal de Villa Sombrero'),
	 ('Junta de Distrito Municipal de Villa Sonador'),
	 ('Junta de Distrito Municipal de Villarpando'),
	 ('Junta de Distrito Municipal de Yaque'),
	 ('Junta de Distrito Municipal de Yásica Arriba');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Junta de Distrito Municipal de Yerba Buena'),
	 ('Junta de Distrito Municipal de Zambrana Abajo'),
	 ('Junta de Retiro de la Policía Nacional'),
	 ('Junta de Retiro de las Fuerzas Armadas'),
	 ('Junta Monetaria'),
	 ('La Jagua'),
	 ('Laboratorio Nacional de Salud Pública Dr. Defilló'),
	 ('Laboratorio Veterinario Central'),
	 ('Liceo Secundario Padre Fantino Cruce de Barranca'),
	 ('Liga Municipal Dominicana');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Los Fríos'),
	 ('Lotería Nacional'),
	 ('Mercados Dominicanos de Abasto Agropecuario'),
	 (' Ministerio Administrativo de la Presidencia'),
	 ('Ministerio de Administración Pública'),
	 ('Ministerio de Agricultura'),
	 ('Ministerio de Cultura'),
	 ('Ministerio de Defensa – MIDE'),
	 ('Ministerio de Deportes y Recreación – MIDEREC'),
	 ('Ministerio de Economía');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ministerio de Educación Superior'),
	 ('Ministerio de Educación – MINERD'),
	 ('Ministerio de Energía y Minerías – MEM'),
	 ('Ministerio de Hacienda'),
	 ('Ministerio de Industria'),
	 ('Ministerio de Interior y Policía – MIP'),
	 ('Ministerio de la Juventud'),
	 ('Ministerio de la Mujer'),
	 ('Ministerio de la Presidencia – MINPRE'),
	 ('Ministerio de la Vivienda');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Ministerio de Medio Ambiente y Recursos Naturales'),
	 ('Ministerio de Obras Públicas y Comunicaciones – MOPC'),
	 ('Ministerio de Relaciones Exteriores – MIREX'),
	 ('Ministerio de Salud Pública y Asistencia Social – MSP'),
	 ('Ministerio de Trabajo – MT'),
	 ('Ministerio de Turismo – MITUR'),
	 ('Ministerio Público – PGR'),
	 ('Museo del Hombre Dominicano'),
	 ('Museo Nacional de Historia Natural “Prof. Eugenio de Jesús Marcano”'),
	 ('Museo Policial Dominicano');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('No Aplica'),
	 ('Oficina Coordinadora General del Fideicomiso PARQUÉAT_RD.'),
	 ('Oficina de Cooperación Internacional'),
	 ('Oficina de Coordinación Presidencial'),
	 ('Oficina de Custodia y Administración de Bienes Incautados y Decomisados'),
	 ('Oficina de Ingenieros Supervisores de Obras del Estado'),
	 ('Oficina de la Defensa Civil'),
	 ('Oficina de Tratados Comerciales Agrícolas'),
	 ('Oficina Equidad de Genero de la Policía Nacional'),
	 ('Oficina Gubernamental de Tecnología de la Información y la Comunicación');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Oficina Metropolitana de Servicios de Autobuses'),
	 ('Oficina Nacional de Defensa Pública'),
	 ('Oficina Nacional de Derecho de Autor'),
	 ('Oficina Nacional de Estadística'),
	 ('Oficina Nacional de Evaluación Sísmica y Vulnerabilidad de Infraestructura y Edificaciones'),
	 ('Oficina Nacional de la Propiedad Industrial'),
	 ('Oficina Nacional de Meteorología'),
	 ('Oficina Nacional de Patrimonio Cultural Subacuático'),
	 ('Oficina para el Reordenamiento del Transporte'),
	 ('Oficina Presidencial de Iniciativas Democráticas');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Oficina Técnica de Transporte Terrestre'),
	 ('Organismo Dominicano de Acreditación'),
	 ('Orquesta Sinfónica Nacional'),
	 ('Parque Zoológico Nacional Arq. Manuel Valverde Podesta'),
	 ('Plan de Asistencia Social de la Presidencia'),
	 ('Plan Presidencial Contra la Pobreza'),
	 ('Presidencia de la República'),
	 ('Prestadora de Servicios de Estancias Infantiles Salud Segura'),
	 ('Procuraduría Fiscal del Distrito Judicial del Distrito Nacional'),
	 ('Procuraduría Fiscal Provincia Santo Domingo');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Programa de Administración Financiera Integrada'),
	 ('Programa de Medicamento de Alto Costo y Ayudas Directas – Ministerio de Salud Pública'),
	 ('Programa de Medicamentos Esenciales/Central de Apoyo Logístico'),
	 ('Programa de Medicamentos Esenciales/Central de Apoyo Logístico'),
	 ('Programa Supérate'),
	 ('Proyecto La Cruz de Manzanillo'),
	 ('Refinería Dominicana de Petróleo'),
	 ('Rehabilitación Sicosocial y Desarrollo Humano'),
	 ('Repetida Hospital Municipal Dr. Pedro Heredia Rojas Giovanni'),
	 ('Secretaría Técnica de Soberanía y Seguridad Alimentaria y Nutricional');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Seguro Nacional de Salud'),
	 ('Senado de la República Dominicana'),
	 ('Servicio Geológico Nacional'),
	 ('Servicio Nacional de Protección Ambiental'),
	 ('Servicio Nacional de Salud'),
	 ('Servicio Regional de Salud Cibao Central'),
	 ('Servicio Regional de Salud Cibao Occidental'),
	 ('Servicio Regional de Salud El Valle'),
	 ('Servicio Regional de Salud Enriquillo'),
	 ('Servicio Regional de Salud Este');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Servicio Regional de Salud Metropolitano'),
	 ('Servicio Regional de Salud Norcentral'),
	 ('Servicio Regional de Salud Nordeste San Francisco de Macorís'),
	 ('Servicio Regional de Salud Valdesia'),
	 ('Servicios Militar Voluntario'),
	 ('Sistema Nacional de Atención a Emergencias y Seguridad 911 Zona Metro'),
	 ('Sistema Nacional de Atención a Emergencias y Seguridad 911 Zona Norte'),
	 ('Sistema Único de Beneficiarios'),
	 ('Subjefatura de la Policía Nacional'),
	 ('Superintendencia de Bancos');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Superintendencia de Electricidad'),
	 ('Superintendencia de Pensiones'),
	 ('Superintendencia de Salud y Riesgos Laborales'),
	 ('Superintendencia de Seguros'),
	 ('Superintendencia de Vigilancia y Seguridad Privada'),
	 ('Superintendencia del Mercado de Valores'),
	 ('Suprema Corte de Justicia'),
	 ('Teatro Nacional'),
	 ('Tesorería de la Seguridad Social'),
	 ('Tesorería Nacional');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Tribunal Constitucional'),
	 ('Tribunal Superior Electoral'),
	 ('Unidad de Análisis Financiero'),
	 ('Unidad de Electrificación Rural y Sub-Urbana'),
	 ('Unidad de Evaluación y Seguimiento de los Proyectos'),
	 ('Unidad de Niños Quemados Dra Thelma Rosario'),
	 ('Unidad de Salud Mental Prof. Ramón Rey Ardid'),
	 ('Unidad Ejecutora para la Readecuación de Barrios y Entornos'),
	 ('Unidad Técnica Ejecutora de Proyectos de Desarrollo Agroforestal'),
	 ('Unidad Técnica Ejecutora de Titulación de Terrenos del Estado');
INSERT INTO instituciones_publicas ("institucion") VALUES
	 ('Universidad Autónoma de Santo Domingo'),
	 ('Universidad Tecnológica del Cibao Oriental'),
	 ('Vicepresidencia de la República'),
	 ('Gabinete Social – GCPS'),
	 ('Administradora de Estancias Infantiles Salud Segura'),
	 ('Administración General del Parque Nacional Mirador Norte'),
	 ('Acuario Nacional'),
	 ('Academia Militar Batalla de las Carreras');
